# SQL

## Comments

Comments can be inserted on a separate line or within a Transact-SQL statement. Multiple-line comments must be indicated by /* and */. A stylistic convention often used for multiple-line comments is to begin the first line with /*, subsequent lines with **, and end with */. There is no maximum length for comments


# Relational Data Model

## Important terms

1. **Relation** - A Two dimensional table that represents table that represents some entity or relationship
2. **Entity** - Abstraction of a real life object like a car
3. **Relationship** - Defines how entities are connected
4. **Attribute** - A colum in a table
5. **Tuple** - Is a row in a table

## Rules and restrictions

1. There cannot be two relation with the same name in a database
2. All attributes within the same relation should have different names
3. there should only be one value in each cell
4. The order of the rows and columns is not important

## Integrety

**Entity integrity**: This means that you can not have two identical tuples(rows) in the table. To maintain this integrity we use **primary keys (PK)**. This PK is a field or a set of field that are used that is used to uniquely identify every record in the database.

**Referential integrity** accours when we have two connected relations. This relationship is provided a **foreign key(FK)**. A FK ina table is the reference to the PK of another table.

## Relationships

1. **one-to-one relationship (1-1)** - One row in the first table can be associated with no more than tuple of another relation.
2. **one-to-may relationship (1-M)** - Means that a row in the fist table can multiple assosiated rows in an other table
3. **many-to-many relationship (M-M)** - A set of tuples can have an associated set in another table (De Facto never happens, while use a central table to turn M-M into two 1-M)

# Result ordering

To specify the order of the reslulting rows you should use `ORDER BY` in the querry.

SELECT
    hotel_id,
    hotel_name,
    price_per_night,
    price_for_early_check_in,
    rating,
    stars
FROM
    hotels
ORDER BY
    price_per_night
;

This example can also sort for two night with early check in.

SELECT
    hotel_id,
    hotel_name,
    price_per_night,
    price_for_early_check_in,
    rating,
    stars
FROM
    hotels
ORDER BY
    price_per_night*2 + price_for_early_check_in
;

SELECT
    hotel_id,
    hotel_name,
    price_per_night,
    price_for_early_check_in,
    rating,
    stars
FROM
    hotels
ORDER BY
    rating DESC,
    price_per_night*2 + price_for_early_check_in
;

SELECT
    hotel_name,
    price_per_night*2 + price_for_early_check_in AS total_price,
    rating,
    stars
FROM
    hotels
ORDER BY
    total_price, 3 DESC
;

# Aggregate functions

When you need to combine the data of multiple cells, you can use aggregate functions.

Here is a list of aggregate functions:
* MIN
* MAX
* AVG
* COUNT
* SUM

## Examples of usage

SELECT MAX(price)
FROM stocks;

SELECT SUM(yesterday_deals)
FROM stocks;

SELECT
    AVG(price) AS avg_price,
    AVG(yesterday_deals) AS avg_deals
FROM
    stocks
WHERE
    price > 40;

DISTINCT allows you to omit all duplicate values.

SELECT COUNT(DISTINCT yesterday_deals)
FROM stocks;

# `GROUP BY`

SELECT
    stock_name,
    MAX(price) AS maximum
FROM
    stocks
GROUP BY
    stock_name;

| stock_name | maximum |
|------------|---------|
| WTI        | 89.8    |
| FB         | 63.7    |
| DJI        | 52.7    |

## `HAVING`

Queries with a GROUP BY statement are regular in a way that they allow to filter rows with WHERE statement and to order them with ORDER BY statement. There is another clause that is especially helpful with grouping tasks – HAVING. If WHERE accepts conditions on values that certain cells have, HAVING does the same but for values of already computed aggregations. For example, let's select "stock-datetime" pairs with maximum price above 50:

SELECT
    stock_name,
    datetime,
    MAX(price) AS maximum
FROM
    stocks
GROUP BY
    stock_name,
    datetime
HAVING
    MAX(price) > 50;

| stock_name | datetime         | maximum |
|------------|------------------|---------|
| WTI        | 2020-05-17 11:00 | 89.8    |
| FB         | 2004-05-28 21:09 | 63.7    |
| DJI        | 1998-03-31 04:18 | 52.7    |

## Order of evaluation of the statement

1. FROM
2. WHERE
3. GROUP BY
4. HAVING
5. SELECT
6. ORDER BY

# `UPDATE`

Changes department_id from whole set to 14

UPDATE employees
SET department_id = 14;

Update id and increase sallery

UPDATE employees
SET department_id = 14,
salary = salary + 10000;

# Constraints

https://hyperskill.org/learn/step/9587

# Exercises

## 1/4

Find students who are in 3rd grade and have 5 points for all their courses.
The output should consist of the student names only in alphabetical order.

select
    Students.name
from main.Students
inner join Student_Subject subject
    on Students.student_id = subject.student_id
where
    Students.grade = 3
group by
    Students.name,
    Students.grade
having
    min(subject.result) >= 5
order by
    Students.name
























